config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'

  # must include in url /author/posts/...
  namespace :authors do
    resources :posts
  end

  # don't include in url /posts/...
  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact

    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author

  scope :most_recent, -> { order(id: :desc) }

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    "Published #{created_at.strftime('%-b %-d, %Y')}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.all
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        # @post = Post.find(params[:id])
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        # params.require(:post).permit(:title, :body, :description, :slug)
        params.require(:post).permit(:title, :body, :description, :banner_image_url)
      end
  end
end

app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < ApplicationController
    def about
    end

    def contact
    end
  end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < ApplicationController
    # GET /posts
    # GET /posts.json
    def index
      # @posts = Post.all
      @posts = Post.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = Post.friendly.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author/posts_helper.rb
module Author::PostsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.haml
= form_for(post, url: url, html: {class: "form-horizontal", role: "form"}) do |f|
  -if post.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(post.errors.count, "error")} prohibited this post from being saved:"

      %ul
        - post.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :banner_image_url, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :banner_image_url, class: 'form-control'
  .form-group
    = f.label :body, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :body, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/authors/posts/_post.html.haml
.col-sm-6.col-lg-4
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        = post.title
    .panel-body
      .thumbnail
        %img{src: "#{post.banner_image_url}"}
      %p.published-date
        = post.display_day_published
      %p
        = truncate(post.description, length: 130)
      %p
        = link_to 'Read', post, class: 'btn btn-sm btn-default'

app/views/authors/posts/edit.html.haml
= provide(:page_title, "Edit #{@post.title}")
= provide :author, "active"

.page-header
  = link_to authors_posts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to authors_post_path(@post), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing post

= render 'form', post: @post, url: authors_post_url(@post)

app/views/authors/posts/index.html.haml
= provide(:page_title, "All Posts")
= provide :author, "active"

.page-header
  = link_to new_authors_post_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Post
  %h1 Listing posts

// .row
//   - @posts.each do |post|
//     = render 'post', post: post

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th.text-center Title
        %th.text-center Action
    %tbody
      - @posts.each do |post|
        %tr
          %td= link_to "#{post.title}", authors_post_path(post)
          %td
            = link_to 'CHANGE', edit_authors_post_path(post), class: 'btn btn-sm btn-warning'
            %span |
            = link_to 'REMOVE', authors_post_path(post), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-sm btn-danger'

app/views/authors/posts/new.html.haml
= provide(:page_title, "New Post")
= provide :author, "active"

.page-header
  = link_to authors_posts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New post

= render 'form', post: @post, url: authors_posts_url

app/views/authors/posts/show.html.haml
= provide(:page_title, "Show #{@post.title}")
= provide :author, "active"

.page-header
  = link_to authors_posts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_authors_post_path(@post), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show post

.row
  .col-sm-8
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          = @post.title
      .panel-body
        .thumbnail
          %img{src: "#{@post.banner_image_url}"}
        %p.published-date
          = @post.display_day_published
        %p
          = @post.body.html_safe

// %dl.dl-horizontal
//   %dt Title:
//   %dd= @post.title
//   %dt Body:
//   %dd= @post.body
//   %dt Description:
//   %dd= @post.description
//   %dt Slug:
//   %dd= @post.slug

app/views/blog/pages/about.html.haml
= provide(:page_title, "About")
= provide :about_active, "active"

.page-header
  %h1 Page#about
%p Find me in app/views/page/about.html.haml

app/views/blog/pages/contact.html.haml
= provide(:page_title, "Contact")
= provide :contact_active, "active"

.page-header
  %h1 Page#contact
%p Find me in app/views/page/contact.html.haml

app/views/blog/posts/_form.html.haml
= form_for @post, html: { class: "form-horizontal", role: "form" } do |f|
  -if @post.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"

      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :banner_image_url, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :banner_image_url, class: 'form-control'
  .form-group
    = f.label :body, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :body, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/blog/posts/_post.html.haml
.col-sm-6.col-lg-4
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        = post.title
    .panel-body
      .thumbnail
        %img{src: "#{post.banner_image_url}"}
      %p.published-date
        = post.display_day_published
      %p
        = truncate(post.description, length: 130)
      %p
        = link_to 'Read', post, class: 'btn btn-sm btn-default'

app/views/blog/posts/edit.html.haml
= provide(:page_title, "Edit #{@post.title}")
= provide :blog_active, "active"

.page-header
  = link_to posts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @post, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing post

= render 'form'

app/views/blog/posts/index.html.haml
= provide(:page_title, "All Posts")
= provide :blog_active, "active"

.page-header
  // = link_to new_post_path, class: 'btn btn-primary' do
  //   %span.glyphicon.glyphicon-plus
  //   New Post
  %h1 Listing posts

.row
  - @posts.each do |post|
    = render 'post', post: post

app/views/blog/posts/new.html.haml
= provide(:page_title, "New Post")
= provide :blog_active, "active"

.page-header
  = link_to posts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New post

= render 'form'

app/views/blog/posts/show.html.haml
= provide(:page_title, "Show #{@post.title}")
= provide :blog_active, "active"

.page-header
  = link_to posts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  // = link_to edit_post_path(@post), class: 'btn btn-primary' do
  //   %span.glyphicon.glyphicon-pencil
  //   Edit
  %h1 Show post

.row
  .col-sm-8
    .panel.panel-default
      .panel-heading
        %h4.panel-title
          = @post.title
      .panel-body
        .thumbnail
          %img{src: "#{@post.banner_image_url}"}
        %p.published-date
          = @post.display_day_published
        %p
          = @post.body.html_safe

// %dl.dl-horizontal
//   %dt Title:
//   %dd= @post.title
//   %dt Body:
//   %dd= @post.body
//   %dt Description:
//   %dd= @post.description
//   %dt Slug:
//   %dd= @post.slug

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Project name", root_path, class: "navbar-brand"
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: "#{yield(:blog_active)}"}
          = link_to 'Blog', root_path
        %li{class: "#{yield(:about_active)}"}
          = link_to 'About', about_path
        %li{class: "#{yield(:contact_active)}"}
          = link_to 'Contact', contact_path
        - if author_signed_in?
          %li{class: "#{yield(:author)}"}
            = link_to 'My Post', authors_posts_path
          %li
            = link_to 'Sign Out', destroy_author_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = "#{yield(:page_title)} | Blog"
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    %div{class: "container #{controller_name} #{action_name}"}
      // %p.notice= notice
      // %p.alert= alert
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/layouts/author.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = "#{yield(:page_title)} | Blog"
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    %script{src: "//cdn.tinymce.com/4/tinymce.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    %div{class: "container #{controller_name} #{action_name}"}
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield